### PR TITLE
Add detailed explanation of MCPM hyperparameters used

### LINKED ISSUE #82: Descriptions of hyperparameters in README file
A description of the hyperparameters on the top left of the GUI (e.g., sensing distance) is not explicitly given in written form anywhere. It would be very helpful to have such a list in the README file.

### PR DESCRIPTION
**Pull request by Abhinavcode13**
- Fixes #82 

Added description for the following hyperparameters : Sensing dist, Sensing angle, Sampling expo, Step size, Data deposit, Agent deposit, Deposit attn, Trace attn, Deposit vis and Trace vis

### CODE REVIEW

**Comment by kirandeol** [comment]
Hello, thank you for your contribution! For now, please avoid merging changes without a review from someone on the PolyPhy team. Since I do not help manage this particular repository I am not the best person to seek a review from. Please wait for either @pjflux2001 or @OskarElek to review your request. Thank you!

**Comment by Abhinavcode13** [comment]
Yes, @kirandeol, I didn't merge any other PRs, this seems to be fine in my opinion, and as it was mentioned in below snippet

```
        window.GUI.text("Sensing dist: average distance in world units at which agents probe the deposit")
        window.GUI.text("Sensing angle: angle in radians within which agents probe deposit (left and right concentric to movement direction)")
        window.GUI.text("Sampling expo: sampling sharpness (or 'acuteness' or 'temperature') which tunes the directional mutation behavior")
        window.GUI.text("Step size: average size of the step in world units which agents make in each iteration")
        window.GUI.text("Data deposit: amount of marker 'deposit' that *data* emit at every iteration")
        window.GUI.text("Agent deposit: amount of marker 'deposit' that *agents* emit at every iteration")
        window.GUI.text("Deposit attn: attenuation (or 'decay') rate of the diffusing combined agent+data deposit field")
        window.GUI.text("Trace attn: attenuation (or 'decay') of the non-diffusing agent trace field")
        window.GUI.text("Deposit vis: visualization intensity of the green deposit field (logarithmic)")
        window.GUI.text("Trace vis: visualization intensity of the red trace field (logarithmic)")
```

**Comment by pjflux2001** [comment]
@Abhinavcode13  For future reviews, to streamline the review process, please feel free to assign me as a reviewer once you've completed your own testing. I will make sure to review and merge by the end of the respective week.

**Comment by Abhinavcode13** [comment]
My bad, this won't happen again. ;/ @pjflux2001 , yeah I'll make sure that.

**Pull request merged**
